### ISSUE TITLE
Ground truth for the test images

### ISSUE THREAD

**Issue by selvamathi** [xytmhy/DED-Net-Defocus-Estimation-and-Deblurring#5]
Hi sir, 
Your project is amazing,
do you have ground truth for the test images? 
If possible can you send me that to my email ID (selvamathi2001@gmail.com)

**Comment by addy1997** [comment]
Hi @selvamathi,

I am getting this error after running the python file `main.py`. Note: I downloaded the dataset zip file and extracted it in the root directory of the repository.

Could you help?

```
=> will save everything to defocus_dataset/08-06-05:35/deblurnetde,adam,200epochs,b48,lr0.0001,5
=> fetching img pairs in '/home/adwait/DID-ANet-Defocus-Deblurring/DED_Dataset'
Traceback (most recent call last):
  File "/home/adwait/DID-ANet-Defocus-Deblurring/main.py", line 332, in <module>
    main()
  File "/home/adwait/DID-ANet-Defocus-Deblurring/main.py", line 121, in main
    train_set, test_set = datasets.__dict__[args.dataset](
KeyError: 'defocus_dataset'
 
```

**Comment by selvamathi** [comment]
Sir,

I am also getting the same error while running the main code. I am not able
to clear the error. But the testing code is easier to debug than the main
code.

Thanking you,

Yours sincerely,

Selvamathi

**Comment by addy1997** [comment]
Thanks

**Comment by RuiWang-coder** [comment]
Dear Haoyu Ma, Thank you very much for the work．
I have the same question, we need the groundtruth of test dataset, could you release the ground truth? That's will be very thankful!!
If possible can you send me that to my [email(wangrui7159@outlook.com)]

**Comment by dompm** [comment]
Hello Mr. Ma,
Very nice work! I'd be interested in the ground truth data for the test set as well. if possible. Here is my email: dompm@hotmail.com.
Thank you!
